pipeline {
	agent any
	parameters {
        booleanParam(name: 'DEPLOY', defaultValue: false, description: 'Toggle this value')
    }	
	stages{
		stage('Upload Key') {
			steps {
				script {
					// Uploads file via master node and stases it for other nodes to access
					def inputFile = input message: 'Upload file', parameters: [file(name: "data.zip")]
					new hudson.FilePath(new File("${workspace}/data.zip")).copyFrom(inputFile)
					inputFile.delete()
				}
				stash name: 'data.zip' , includes: "data.zip"
			}
		}
		stage ('Preparation deploy Infra') {
			when {
				expression { params.DEPLOY == true }
				// expression { params.DESTROY == true }
			}
			steps {
				sh "cd training_terraform && ls && terraform init -plugin-dir=/tmp/terraform_plugin && terraform plan"
			}
		}

		
		stage('Approve deployment') {
			when {
				expression { params.DEPLOY == true }
			}
			steps {
				timeout(time: 7, unit: 'DAYS') {
					script {
						env.APPROVE_DEPLOY = input(message: 'Approve deployment', 
						parameters: [booleanParam(defaultValue: true, 
						description: 'Voulez-vous continuer le deploiement ?', name: 'Approved Deployment')])
					}
				}
			}
		}
		stage('Deploy Infra') {
			when {
        		environment name: 'APPROVE_DEPLOY', value: "true"
			}
			steps {
				sh "cd training_terraform && terraform apply -auto-approve"
			}
		}
	}
}