pipeline {
	agent any
	environment{
		ENV = 'dev'
  	}
	parameters {
        booleanParam(name: 'DEPLOY', defaultValue: false, description: 'Toggle this value')
        booleanParam(name: 'DESTROY', defaultValue: false, description: 'Toggle this value')
    }	
	stages{
		stage ('Preparation deploy Infra'){
			when {
				expression { params.DEPLOY == true }
				expression { params.DESTROY == true }
			}
			steps {
				sh "cd training_terraform && ls && terraform init -plugin-dir=/tmp/terraform_plugin && terraform plan"
			}
		}
		stage('Approve deployment') {
            when {
                expression { params.DESTROY == true }
            }
            steps {
                timeout(time: 7, unit: 'DAYS') {
                    script {
                        env.APPROVE_DEPLOY = input(message: 'Approve deployment',
                        parameters: [booleanParam(defaultValue: true,
                        description: 'So you want to delete this?', name: 'Approved Deployment')])
                    }
                }
            }
        }
        stage ('Destroy Infra'){

            when {
                expression { params.DESTROY == true }
             }
            steps {
                sh "cd training_terraform && terraform destroy -auto-approve"
            }
        }
		stage('Approve deployment') {
			when {
				expression { params.DEPLOY == true }
			}
			steps {
				timeout(time: 7, unit: 'DAYS') {
					script {
						env.APPROVE_DEPLOY = input(message: 'Approve deployment', 
						parameters: [booleanParam(defaultValue: true, 
						description: 'Voulez-vous continuer le deploiement ?', name: 'Approved Deployment')])
					}
				}
			}
		}
		stage ('Deploy Infra'){
			when {
        		environment name: 'APPROVE_DEPLOY', value: "true"
			}
			steps {
				sh "cd training_terraform && terraform apply -auto-approve"
			}
		}
	}
}
